import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navigation/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-emerald-50`}>
        <Navbar />
        <div className="container mx-auto p-4 sm:p-0 sm:py-4">{children}</div>
      </body>
    </html>
  );
}
